/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

/*
This class includes custom icons from online, used in the about/homepage design
and for social media external links.
*/

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String _kFontPkg = null;

  static const IconData eyeglass = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analysis = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ig = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fb = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpinghands = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearthands = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fist_raised = IconData(0xf6de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
